CREATE TABLE IF NOT EXISTS contactos (
  id              INT NOT NULL AUTO_INCREMENT,
  tenant_id       INT NOT NULL,
  nombre          VARCHAR(200) NOT NULL,
  apellido        VARCHAR(200) NULL,
  email           VARCHAR(200) NULL,
  telefono        VARCHAR(50) NULL,
  whatsapp        VARCHAR(50) NULL,
  empresa         VARCHAR(200) NULL,
  cargo           VARCHAR(100) NULL,
  etiquetas       JSON NULL,
  fuente          ENUM('web','whatsapp','manual','ads','referido') NOT NULL DEFAULT 'manual',
  score_ia        TINYINT NULL DEFAULT 0,
  notas           TEXT NULL,
  activo          TINYINT(1) NOT NULL DEFAULT 1,
  creado_en       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_contactos_tenant (tenant_id),
  INDEX idx_contactos_email (email),
  FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE CASCADE
);
