CREATE TABLE IF NOT EXISTS ventas_leads (
  id                  INT NOT NULL AUTO_INCREMENT,
  nombre              VARCHAR(200) NOT NULL,
  empresa             VARCHAR(200) NULL,
  email               VARCHAR(200) NULL,
  telefono            VARCHAR(50) NULL,
  rubro_interes       VARCHAR(100) NULL,
  plan_interes        ENUM('starter','pro','plan_ia','enterprise') NULL,
  fuente              ENUM('web','referido','ads','evento','cold') NOT NULL DEFAULT 'web',
  estado              ENUM('nuevo','contactado','demo','propuesta','cerrado','perdido') NOT NULL DEFAULT 'nuevo',
  asignado_a          INT NULL,
  valor_mrr_estimado  DECIMAL(10,2) NULL,
  notas               TEXT NULL,
  creado_en           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actualizado_en      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_ventas_leads_estado (estado),
  INDEX idx_ventas_leads_asignado (asignado_a),
  FOREIGN KEY (asignado_a) REFERENCES usuarios(id) ON DELETE SET NULL
);
